apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-sample
    app.kubernetes.io/part-of: application-sample
  name: component-sample
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: jvm-build-test-project
      app.kubernetes.io/instance: component-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jvm-build-test-project
        app.kubernetes.io/instance: component-sample
    spec:
      containers:
      - image: quay.io/redhat-appstudio/sample-image@sha256:cb64ac7066616afd7f587a14dab52bc5eb631a17f97e3ac8c223716bbaf79e5c
        name: jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
